package net.azeti.challenge.recipe.service;

import net.azeti.challenge.recipe.dto.RecipeRequest;
import net.azeti.challenge.recipe.dto.auth.RegistrationRequest;
import net.azeti.challenge.recipe.dto.auth.RegistrationResult;
import net.azeti.challenge.recipe.dto.auth.LoginRequest;
import net.azeti.challenge.recipe.user.TokenResponse;

public interface UserService {

    /**
     * Creates a new {@link net.azeti.challenge.recipe.model.User} in the database from the provided {@link RecipeRequest}.
     * @param registrationRequest DTO containing user data to be registered.
     * @return {@link RegistrationResult} DTO containing the registered {@link net.azeti.challenge.recipe.model.User} data.
     */
    RegistrationResult registerUser(RegistrationRequest registrationRequest);

    /**
     * Get the user {@link TokenResponse} generated by JWT.
     * @param loginRequest DTO containing user data from existing {@link net.azeti.challenge.recipe.model.User}.
     * @return {@link TokenResponse} DTO containing the authentication token for {@link net.azeti.challenge.recipe.model.User}.
     */
    TokenResponse login(LoginRequest loginRequest);
}
